[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "plot-primes"
version = "0.0.1"
dependencies = [
  "numpy",
  "matplotlib",
]

[project.scripts]
plot-primes = "plotprimes:main"
